### PR TITLE
Fix.nonzero.exit & Add exit CLI option to force exit 

### LINKED ISSUE #24: Nemo exits with status code 0 even for failing tests
Running into this issue on Jenkins. The build is not failing even if the tests fail because Nemo exits with status `0`

### LINKED ISSUE #29: Support CLI option `exit` to force exit after mocha done running the tests
In mocha versions <4, mocha kill itself after it is done with running all the tests. From mocha versions >=4 mocha will be still alive when any active handles are still on the event loop and the process will just hang. If we are running mocha through command line there is an option to handle it by passing `--exit` option to mocha. Since we are using mocha programmatically in Nemo, we cannot pass it as a mocha option in the config. So, it would be great if we have a CLI option that we can pass to Nemo something like this `nemo --exit` to force exit by shutting down the event loop. We can keep the default behavior of `no-exit` if it is not passed as command line argument

### PR DESCRIPTION
**Pull request by sairamnutheti**
Resolves #24 & #29

### CODE REVIEW

File: lib/console.js [hunk 1]
```diff
@@ -17,4 +17,7 @@ module.exports = function (context, _instances) {
   });
   tabl.push(['TOTALS', output.totals.pass, output.totals.fail, output.totals.total]);
   console.log(tabl.toString());
+  if (context.program.exit) {
+    process.exit(Math.min(output.totals.fail, 255));
```
Comment (grawk) [inline lib/console.js]: Since you're modifying this code, do you want to consolidate the changes in from #30 ?

Comment (sairamnutheti) [reply lib/console.js]: Sure Matt will do

**Comment by grawk** [comment]
looks good. thanks!
